### ISSUE TITLE
verbose=1 throws AttributeError: 'StackingClassifier' object has no attribute 'clf_'

### ISSUE THREAD

**Issue by bdore** [rasbt/mlxtend#91]
First of all thank you Sebastian for the great work on this library.

Here's my code:

```
clf1 = RandomForestClassifier(n_estimators=10, n_jobs=-1, criterion='gini',random_state=42)

clf2 = RandomForestClassifier(n_estimators=10, n_jobs=-1, criterion='entropy',random_state=42)

clf3 = ExtraTreesClassifier(n_estimators=10,random_state=42,n_jobs=-1)

clf4 = ExtraTreesClassifier(n_estimators=10, n_jobs=-1, criterion='entropy',random_state=42)

clf5 = GradientBoostingClassifier(learning_rate=0.05, subsample=0.5, 
max_depth=6, n_estimators=10,random_state=42)

lr = LogisticRegression()
sclf = StackingClassifier(classifiers=[clf1,clf2,clf3,clf4,clf5], 
                          meta_classifier=lr,use_probas=True)

print('3-fold cross validation:\n')

for clf, label in zip([clf1,clf2,clf3,clf4,clf5,sclf], 
                      ['RF Gini', 
                       'RF Entropy',
                       'Xtra Tree 1',
                       'Xtra tree 2',
                       'Grad Boost',
                       'StackingClassifier']):

    scores = cross_validation.cross_val_score(clf, train_no_events, y, 
                                              cv=3, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" 
          % (scores.mean(), scores.std(), label))
```

It all goes well like this but if I add verbose=1 to StackingClassifier() I get a traceback:

```
3-fold cross validation:

Accuracy: 0.63 (+/- 0.01) [RF Gini]
Accuracy: 0.63 (+/- 0.01) [RF Entropy]
Accuracy: 0.63 (+/- 0.01) [Xtra Tree 1]
Accuracy: 0.63 (+/- 0.01) [Xtra tree 2]
Accuracy: 0.64 (+/- 0.00) [Grad Boost]
Fitting 5 classifiers...
Traceback (most recent call last):

  File "<ipython-input-8-29daf2b04330>", line 21, in <module>
    cv=3, scoring='accuracy')

  File "C:\Anaconda3\lib\site-packages\sklearn\cross_validation.py", line 1433, in cross_val_score
    for train, test in cv)

  File "C:\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):

  File "C:\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)

  File "C:\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)

  File "C:\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 180, in __init__
    self.results = batch()

  File "C:\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]

  File "C:\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 72, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]

  File "C:\Anaconda3\lib\site-packages\sklearn\cross_validation.py", line 1531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)

  File "C:\Anaconda3\envs\devel\lib\site-packages\mlxtend\classifier\stacking_classification.py", line 95, in fit
    (i, _name_estimators((clf,))[0][0], i, len(self.clf_)))

AttributeError: 'StackingClassifier' object has no attribute 'clf_'
```

Thanks!

**Comment by rasbt** [comment]
Thanks for letting me know, Bernardo. This issue sounds somewhat familiar to me and it should be fixed in the current dev version (e.g., see #76 ). I should really make a new release version soon, but for now you could install the dev version via `pip install git+git://github.com/rasbt/mlxtend.git or upgrade` it via `pip install git+git://github.com/rasbt/mlxtend.git  --upgrade --no-deps`.
